### ISSUE TITLE
Couldn't build apk on simulator. Conflict with Android dependency com.google.android.gms:play-services-ads-base

### ISSUE THREAD

**Issue by theneshfmt** [YoussefKababe/admob_flutter#10]
Using this plugin along with the firebase admob, gives the below issue while building. I guess this is due to the version conflicts of the dependency.

Launching lib/main.dart on Android SDK built for x86 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture fingerprint of input files for task ':app:checkDebugClasspath' property 'runtimeClasspath' during up-to-date check.
> The library com.google.android.gms:play-services-ads-base is being requested by various other libraries at [[17.0.0,17.0.0], [17.1.1,17.1.1]], but resolves to 17.1.1. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by kyungjoongo** [comment]
Same Issue

**Comment by kyungjoongo** [comment]
To solve this,
Add the following at the bottom of /android/app/build.gradle.
-----------------------------------------------------------------


configurations.all {
    resolutionStrategy {
        force 'com.android.support:support-v4:27.1.1'
        force 'com.google.android.gms:play-services-ads:17.0.0' 
    }
}

**Comment by thaerhamza** [comment]
not working

**Comment by kmcgill88** [comment]
@theneshfmt  whats the status of this issue? Can we close?

**Comment by theneshfmt** [comment]
I've switched to different plugin, so closing this.

**Comment by Purus** [comment]
May I know which package you are using as an alternative?

Thanks,

Purusothaman Ramanujam

**Comment by theneshfmt** [comment]
Hi @Purus I'm using [flutter_google_ad_manager.](https://pub.dev/packages/flutter_google_ad_manager)

**Comment by Purus** [comment]
Thanks for your reply. I was not sure how to use this as I wasn't sure how
to configure AdMob ads using this.

Thanks,

Purusothaman Ramanujam
