### ISSUE TITLE
Error while building for iOS Simulator

### ISSUE THREAD

**Issue by wasibpkr** [YoussefKababe/admob_flutter#11]
Terminal. Xcode Output

    /Users/wasibe/development/tools/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.1.2/ios/Classes/AdmobBanner.swift:6:9: error: editor placeholder in source file
            <#code#>
            ^
    /Users/wasibe/development/tools/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.1.2/ios/Classes/AdmobBannerFactory.swift:7:9: error: editor placeholder in source file
            <#code#>
            ^
    /Users/wasibe/development/tools/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.1.2/ios/Classes/AdmobBanner.swift:6:9: error: editor placeholder in source file
            <#code#>
            ^
    /Users/wasibe/development/tools/flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.1.2/ios/Classes/AdmobBannerFactory.swift:7:9: error: editor placeholder in source file
            <#code#>
            ^

AdmobBannerFactory.swift
--------------------------
import Flutter
import Foundation

public class AdmobBannerFactory: NSObject, FlutterPlatformViewFactory {
    
    public func create(withFrame frame: CGRect, viewIdentifier viewId: Int64, arguments args: Any?) -> FlutterPlatformView {
        <#code#>
    }
}

AdmobBanner.swift
-------------------
import Flutter
import Foundation

public class AdmobBanner: NSObject, FlutterPlatformView {
    public func view() -> UIView {
        <#code#>
    }
}

**Comment by wasibpkr** [comment]
And Working Fine in Android Devices

**Comment by Mapk26** [comment]
Same issue,
all is (almost) fine with android but not building for iOS.

Any update about it?

PS: @YoussefKababe great job, I hope you can continue to improve this plugin.

**Comment by kmcgill88** [comment]
Version 0.3.0 has the first implementation for ios added. @Mapk26 @wasibpkr
