### ISSUE TITLE
Interstitials will not be called.

### ISSUE THREAD

**Issue by kyungjoongo** [YoussefKababe/admob_flutter#14]
There is no trouble installing the package.
Then install the firebase_admob package
Running interstitial ads works well.

However, when you install the admob_flutter package and invoke interstitial ads
Interstitials will not be called.
(interstitialAd.load (); When I execute,The ad will not load.)

Can you use it in duplicate?

So I had to change to the firebase_admob package.

**Comment by kmcgill88** [comment]
I think the answer to this is, pick one library or the other. Closing this issue for now.
