### ISSUE TITLE
Update to AndroidX

### ISSUE THREAD

**Issue by Purus** [YoussefKababe/admob_flutter#17]
As the support the old Android support libs are going to be stopped, it is now required to update the package to use AndroidX.

All the official first-party plugins are already migrated to AndroidX support libs by the Flutter team.

**Comment by Purus** [comment]
I tried migrating to AndroidX but failed.. Any help would be appreciated to port this package to AndroiX. this is the only plugin that can help wtih Native view.

**Comment by davidgalarza** [comment]
I try to follow this: 
https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility#for-plugin-maintainers-migrating-a-flutter-plugin-to-androidx, but I got that "No usages found".

**Comment by Purus** [comment]
Did you had any luck with the update? @davidgalarza

**Comment by davidgalarza** [comment]
No @Purus, I was not lucky, I have problems following the migration guide.

**Comment by angel1st** [comment]
@YoussefKababe - consider #20 is ready to merge, could please shed some light on the timing? Thanks!

**Comment by YoussefKababe** [comment]
@angel1st it's merged now! Thanks for the support everyone!
