### ISSUE TITLE
Need iOS help?

### ISSUE THREAD

**Issue by kmcgill88** [YoussefKababe/admob_flutter#2]
Hi @YoussefKababe,

Awesome work on this plugin! I have an immediate need for banner and interstitial on Android __and__ iOS. I'm newer to Flutter and am still researching PlatformViews however I have experience in iOS.  Are you open to PR's?

**Comment by YoussefKababe** [comment]
Hi @kmcgill88! Happy that you found this useful and want to contribute. Thank you so much! I regret to tell you that the plugin is not open to PRs at the moment. It will be later when I feel it's in a good shape and has everything I planned to build. And between, I've made some good progress on iOS already and will release it in the next days!

**Comment by kmcgill88** [comment]
I understand completely. I will patiently wait to see your iOS work! In the meantime I will study up on the `PlatformViews` so I can help with some PR's if needed. Cheers!

**Comment by YoussefKababe** [comment]
Sounds amazing! This article from Felix was my starting point in the world of PlatformViews: https://medium.com/flutter-community/flutter-platformview-how-to-create-flutter-widgets-from-native-views-366e378115b6

There's also this recent one for creating PlatformViews with Swift: https://medium.com/@phoomparin/how-to-use-native-uis-in-flutter-with-swift-platform-view-8b4dc7f833d8

And there's as well official documentation from Flutter for iOS stuff: https://docs.flutter.io/objcdoc/Protocols/FlutterPlatformView.html

Cheers!

**Comment by kmcgill88** [comment]
Lol, I was just reading one of those! Thanks for sharing!

**Comment by kmcgill88** [comment]
Hey @YoussefKababe, any updates on iOS?

**Comment by ethanblake4** [comment]
@kmcgill88 : since @YoussefKababe seems to be MIA, would you be interested in collaborating on a fork of this package with iOS support? I can handle future updates on the Android side, but I don't have a ton of iOS experience. Email me ethanblake@gmail.com

**Comment by kmcgill88** [comment]
Hi @ethanblake4, I found another solution for now on iOS. Hopefully @YoussefKababe get's some time to work on iOS. This is a promising plugin. If he doesn't respond soon I might take you up on the offer though.

**Comment by YoussefKababe** [comment]
Hi @ethanblake4 and @kmcgill88! I'm really sorry for not pushing updates for this package, and not having time to add iOS support. I'm having some busy days at my current day job, a lot of work and much time needed there. I will be happy to receive your PRs here guys, and I will also be back to work on this ASAP. I promise!

**Comment by praven07** [comment]
Hey @YoussefKababe are you gonna be doing the iOS support?

**Comment by ArthurianX** [comment]
@kmcgill88 - What is your solution for iOS ?

**Comment by kmcgill88** [comment]
@ArthurianX I have an existing lib for ios and admob. Check it out, https://github.com/kmcgill88/McAdViewController

It works but causes initial Flutter start time to be a bit slow. When I get some time I plan on adoing support to this lib for Flutter.

**Comment by ArthurianX** [comment]
@kmcgill88 - Thanks!

**Comment by c4talyst** [comment]
Anyway some of this work can be PR’d into the firebase_admob plug-in? This is amazing - but have a need for iOS too

**Comment by SachinGanesh** [comment]
> I understand completely. I will patiently wait to see your iOS work! In the meantime I will study up on the `PlatformViews` so I can help with some PR's if needed. Cheers!

@kmcgill88 Hi, We @dreamsoftin have implemented **Facebook Audience Network** for Flutter (https://github.com/dreamsoftin/facebook_audience_network). Currently the plugin is **Android only** and it supports Banner, Interstitial, Rewarded Video, In Stream Video & Native Ads. I'm looking for some one who can help us in implementing  iOS part of it. May be you can help us in this?

**Comment by kmcgill88** [comment]
@SachinGanesh Thanks for reaching out. Right now I think I'm going to stick to getting `admob_flutter` up and running for iOS. @YoussefKababe you can add me as a maintainer if you'd like. I don't have a ton of time to dedicate to this project but having more than 1 able to merge PR's might be good.

**Comment by YoussefKababe** [comment]
@kmcgill88 I have just added you as a collaborator. Thank you so much for your time and your help!

**Comment by kmcgill88** [comment]
@YoussefKababe I got Banners working on iOS last night! Still working out some issues though. For some reason, I wasn't seeing the params passed from the Flutter side. I'm sure I'll get it. I'll keep you posted.

I plan to get Interstitial and rewards next then I will PR for review.

**Comment by kmcgill88** [comment]
If anyone else runs into an issue with a platform view not receiving args from Flutter, [this post](https://github.com/flutter/flutter/issues/28124#issuecomment-465944104) was the answer!

**Comment by kmcgill88** [comment]
@YoussefKababe and anyone following this issue. *Progress update:* I have Interstitial ads working! I think I will have time this week to finish rewards. Then this plugin will have feature parity on Android and iOS! 🎉 

@YoussefKababe I'm guessing you are the only one that has `pub` permission to publish an update. A Are you interested in adding me or would you prefer to publish when this ticket is complete? 😄
