### ISSUE TITLE
Upload Readme version of admob_flutter for AndroidX

### ISSUE THREAD

**Issue by TeuryBazzo** [YoussefKababe/admob_flutter#26]
I was trying generate apk of my app and i used the version admob_flutter: "^0.1.2", but this version don't support androidx, so i upload to  admob_flutter: "^0.2.0" and thats work ! i see this alteration in issuie #17, it would be interesting alter readme ?

**Comment by kmcgill88** [comment]
Hi @TeuryBazzo, I agree this should be added to the README. Really the whole package should have been bumped to `1.0.0` since its a major, breaking, change.

Would you be willing to make the PR to update the README with this info?
