### ISSUE TITLE
On release AdMob Banner don't show

### ISSUE THREAD

**Issue by TeuryBazzo** [YoussefKababe/admob_flutter#29]
When i  put unit ID of prodution the banner don't show, but unit ID of test "ca-app-pub-3940256099942544/6300978111" this work.

my code 
`
AdmobBanner(
            adUnitId: 'ca-app-pub-4310356880653109/2595718186',
            adSize: AdmobBannerSize.FULL_BANNER,
          ),
`

Someone went through this ? 
my app is on playstore, [here](https://play.google.com/store/apps/details?id=com.exemple.semvicio)

**Comment by kmcgill88** [comment]
Was it a new ad unit id? I've had new id's take some time to _activate_. Also, did you mark your app as having ads in it on the Play Store?

**Comment by TeuryBazzo** [comment]
yes, id is new and app was marked as contains ad.
Do you know how much time to activate?

**Comment by TeuryBazzo** [comment]
Oh man, my fault.
I did not know that payment method is required in a admob account, now i complete the form and the banner starting show kk
