### ISSUE TITLE
Crashing on iOS: Trying to embed a platform view but the PaintContext does not support embedding

### ISSUE THREAD

**Issue by nemoryoliver** [YoussefKababe/admob_flutter#33]
**ERROR**

```
Unsupported value: Error Domain=com.google.admob Code=8 "Request Error: Cannot find an ad network adapter for mediation." UserInfo={NSLocalizedDescription=Request Error: Cannot find an ad network adapter for mediation.} of type GADRequestError
[VERBOSE-2:platform_view_layer.cc(28)] Trying to embed a platform view but the PaintContext does not support embedding
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001100126fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010f5b6ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000110012482 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010b05b927 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   Flutter                             0x0000000109233f6e -[FlutterStandardWriter writeValue:] + 1958
	5   Flutter                             0x00000001092329c8 -[FlutterStandardMethodCodec encodeMethodCall:] + 136
	6   Flutter                             0x000000010922396d -[FlutterMethodChannel invokeMethod:arguments:] + 58
	7   Runner                              0x00000001050dfab1 $s13admob_flutter11AdmobBannerC6adView_27<…>
[VERBOSE-2:platform_view_layer.cc(19)] Trying to embed a platform view but the PrerollContext does not support embedding
Lost connection to device.
Exited (sigterm)
```

**Comment by nemoryoliver** [comment]
Fixed it by adding this to the root of info.plist _please mention this as a breaking change for now._

```
<key>io.flutter.embedded_views_preview</key>
<true/>
```

**Comment by nemoryoliver** [comment]
Still crashing though when it gets the error

`Unsupported value: Error Domain=com.google.admob Code=8 "Request Error: Cannot find an ad network adapter for mediation." UserInfo={NSLocalizedDescription=Request Error: Cannot find an ad network adapter for mediation.} of type GADRequestError`

**Comment by kmcgill88** [comment]
Adding 

<key>io.flutter.embedded_views_preview</key>
<true/>

Is noted in the read me.


@nemoryoliver I got the same error while using the test ad unit id's in the example. However I pull this into my app with my real ad unit id's and things were fine. 

I also confirmed the -Obj-C flag is set.


Are you only seeing this error in the example app?

**Comment by mmahkamov** [comment]
> @nemoryoliver I got the same error while using the test ad unit id's in the example. However I pull this into my app with my real ad unit id's and things were fine.
> 
> I also confirmed the -Obj-C flag is set.
> 
> Are you only seeing this error in the example app?

It crashes on any error - for example, if the ad fails to load because there's no ad to show (using real IDs).

The crash happens because the method channel cannot encode the NSError type - ```failedToLoad``` expects an int.

I had to remove the error for now:

```
     func adView(_ bannerView: GADBannerView, didFailToReceiveAdWithError error: GADRequestError) {
-         channel.invokeMethod("failedToLoad", arguments: error)
+         channel.invokeMethod("failedToLoad", arguments: nil)
     }
```

It stops crashing on error.

I guess passing ```error.code``` instead of ```error``` itself should also work.

**Comment by nemoryoliver** [comment]
> Adding
> 
> io.flutter.embedded_views_preview
> Is noted in the read me.
> 
> @nemoryoliver I got the same error while using the test ad unit id's in the example. However I pull this into my app with my real ad unit id's and things were fine.
> 
> I also confirmed the -Obj-C flag is set.
> 
> Are you only seeing this error in the example app?

Sorry I got so excited and didn't think of the updated README. Thank you.
I can confirm the Admob warning isn't actually causing the crash. I'm still figuring out what's really causing it. Also, I'm running it on my app and simulator.

**Comment by nemoryoliver** [comment]
> > @nemoryoliver I got the same error while using the test ad unit id's in the example. However I pull this into my app with my real ad unit id's and things were fine.
> > I also confirmed the -Obj-C flag is set.
> > Are you only seeing this error in the example app?
> 
> It crashes on any error - for example, if the ad fails to load because there's no ad to show (using real IDs).
> 
> The crash happens because the method channel cannot encode the NSError type - `failedToLoad` expects an int.
> 
> I had to remove the error for now:
> 
> ```
>      func adView(_ bannerView: GADBannerView, didFailToReceiveAdWithError error: GADRequestError) {
> -         channel.invokeMethod("failedToLoad", arguments: error)
> +         channel.invokeMethod("failedToLoad", arguments: nil)
>      }
> ```
> 
> It stops crashing on error.
> 
> I guess passing `error.code` instead of `error` itself should also work.

Thanks for the workaround, in my case it's not crashing when I get an Admob Warning only when I used the ConditionalBuilder package

**Comment by kmcgill88** [comment]
@nemoryoliver good find! My bad on the bug, I missed that. I bet [this line](https://github.com/YoussefKababe/admob_flutter/blob/master/lib/src/admob_event_handler.dart#L17) on the Dart side could, or somewhere in between, cause the crash. I will get a PR out today to fix. 

`channel.invokeMethod("failedToLoad", arguments: error.code)` seems to work too. My gut says it should be something like this, ` channel.invokeMethod("failedToLoad", arguments: ["error": error.localizedDescription])` so the Dart side actually has some context of the error instead of `nil`. What do you think?

**Comment by mmahkamov** [comment]
Sorry, ```channel.invokeMethod("failedToLoad", arguments: error.code)``` would be wrong.
I checked the Dart side and it expects ```Map<String, dynamic>```

The Kotlin code passes the error code as ```hashMapOf("errorCode" to errorCode)```

I guess you could pass ```["errorCode": error.code, "errorMessage": error.localizedDescription]``` from Swift.

**Comment by kmcgill88** [comment]
Thanks @mmahkamov I'll make the change!

**Comment by kmcgill88** [comment]
```swift
    func adView(_ bannerView: GADBannerView, didFailToReceiveAdWithError error: GADRequestError) {
        channel.invokeMethod("failedToLoad", arguments: [
            "errorCode": error.code,
            "error": error.localizedDescription
        ])
    }
```

Just tested this locally and failing to load a banner does not crash the app anymore. PR soon!

**Comment by nemoryoliver** [comment]
Hi guys! Been out for days sorry for not able to update here. All good now with the latest version! Great job and thanks guys!
