### ISSUE TITLE
Android app crashes on startup

### ISSUE THREAD

**Issue by matte5031** [YoussefKababe/admob_flutter#36]
Hello!

As soon as I add this plugin and try to run the app with both debug and release mode (tried in real device and simulator) it just crashes instantly. I've added this to the AndroidManifestaswell:

    <meta-data
      android:name="com.google.android.gms.ads.APPLICATION_ID"
      android:value="ca-app-pub-3940256099942544~3347511713"/>

Flutter version = 1.6.3 (currently latest beta version)
Dart version = 2.3.2

Any help or input appreciated, thanks!

**Comment by kmcgill88** [comment]
Are you using Android X? This plugin requires it. If you don't want to use Android X then downgrade versions.

**Comment by matte5031** [comment]
Hello! @kmcgill88 
Yes I am using Android X

**Comment by matte5031** [comment]
I saw another open issue where it says "do not support for flutter 1.6"
Is that why it won't work for me maybe? I doesn't support flutter version 1.6 and above? (I use version 1.6.3)

**Comment by kmcgill88** [comment]
@matte5031 could be! I haven't tried the plugin on `1.6.3`. I've only used the stable `1.5.3`. If you debug more and figure something out please post back to this issue.

**Comment by matte5031** [comment]
Okay so the root of the problem was that the meta-data was in the wrong place, it must be within </activity> and </application> tags, this can be closed. thanks

**Comment by kmcgill88** [comment]
Glad you figured it out!

**Comment by sabdelhay** [comment]
> 
> 
> Are you using Android X? This plugin requires it. If you don't want to use Android X then downgrade versions.

Hi,
I'm facing the same problem here, so how to downgrade from AndroidX, it is really makes me too many problems with all AdMob dependencies. I would appreciate your help.
Thank you in advance.
