### ISSUE TITLE
iOS build issue - 'GADMobileAds' has no member 'start'

### ISSUE THREAD

**Issue by ItsCalebJones** [YoussefKababe/admob_flutter#39]
Here is the error when running a build:

SwiftAdmobFlutterPlugin.swift:39:22: error: value of type 'GADMobileAds' has no member 'start'

**Comment by ItsCalebJones** [comment]
I resolved this by having to force Cocoapods to update Firebase/Admob. Cleared the build cache and reloaded the project.

**Comment by CosmoInSpace** [comment]
Would you mind elaborating on the process and perhaps send a gist?

**Comment by ItsCalebJones** [comment]
Here is one way to do it: https://gist.github.com/mbinna/4202236
