### ISSUE TITLE
SMART_BANNER causes error on iOS (iPad)

### ISSUE THREAD

**Issue by hyperpanthera** [YoussefKababe/admob_flutter#46]
LEADERBOARD etc. works.

> BoxConstraints has both negative minimum width and an egative minimum height.
> The offending constraints were:
> BoxConstraints(w=-1.0, h=-2.0; NOT NORMALIZED)

**Comment by kmcgill88** [comment]
I ran into this too. I know you have to wrap the Banner in something that specifies sizes it's allowed to fill. This worked for me on iOS and Android.

```dart
    Container(
          width: MediaQuery.of(context).size.width,
          height: _getHeight(context),
          child: AdmobBanner(
            adUnitId: AdService.getBannerId(),
            adSize: AdmobBannerSize(
              width: MediaQuery.of(context).size.width.toInt(),
              height: _getHeight(context).toInt(),
              name: 'SMART_BANNER',
            ),
            listener: (AdmobAdEvent event, Map<String, dynamic> args) {
              print(event);
            },
          ),
        );
```

I think this could be documented more or maybe a little more intuitive of an API?

**Comment by EliasDeuss** [comment]
I think it should be documented but It would be nice if it could handled that by itself. @kmcgill88

**Comment by kmcgill88** [comment]
If either of you have time to tackle this that would be great. PR's are absolutely welcome!😃

**Comment by EliasDeuss** [comment]
@kmcgill88 What did you do int ```_getHeight(context),``` ?

**Comment by kmcgill88** [comment]
@EliasDeuss  Since I am using a smart banner I just dedicated 6% of the screen height to the banner.

```dart
double _getHeight(BuildContext context) {
    final height = MediaQuery.of(context).size.height;
    final percent = (height * 0.06).toDouble();

    return percent;
  }
```

**Comment by EliasDeuss** [comment]
@kmcgill88 ah smart

**Comment by hyperpanthera** [comment]
> ```dart
> Container(
>           width: MediaQuery.of(context).size.width,
>           height: _getHeight(context),
>           child: AdmobBanner(
>             adUnitId: AdService.getBannerId(),
>             adSize: AdmobBannerSize(
>               width: MediaQuery.of(context).size.width.toInt(),
>               height: _getHeight(context).toInt(),
>               name: 'SMART_BANNER',
>             ),
>             listener: (AdmobAdEvent event, Map<String, dynamic> args) {
>               print(event);
>             },
>           ),
> ```

Thank you it works!

**Comment by DamonChen117** [comment]
In the build method of _AdmobBannerState

for Android:
```
        width: widget.adSize.width >= 0 ? widget.adSize.width.toDouble() : double.infinity,
        height: widget.adSize.height >= 0 ? widget.adSize.height.toDouble() : double.infinity,
```

for IOS
```
        width: widget.adSize.width.toDouble(),
        height: widget.adSize.height.toDouble(),
```

I don't understand why they are different.
