### ISSUE TITLE
[iOS]Tab bar widget  overlaps by banner 

### ISSUE THREAD

**Issue by neestell** [YoussefKababe/admob_flutter#49]
This happens If I put a banner to list of widgets below TabBar widget.
The issue is an order of TabBar widget and list of items should be reversed to work properly. But any way banner is not clipped by list view rect go under TabBar

**Comment by EliasDeuss** [comment]
Can you add a screenshot of what is happening @neestell

**Comment by neestell** [comment]
![IMG_0652](https://user-images.githubusercontent.com/1618447/61036737-7d84ad80-a3eb-11e9-9495-4a6dd7a1eb49.PNG)
ListWidget and TabBarWidget are placed in ColumnWidget vertically

**Comment by PonzyPon** [comment]
@neestell  I had a same issue and resolved. I don't know your codes so I'm not sure it helps you but how about wrapping with `Material` widget?

![スクリーンショット 2019-07-14 11 08 57](https://user-images.githubusercontent.com/11908295/61178465-5961e000-a628-11e9-838c-0dc913d073f0.png)

I didn't get this issue with AppBar, so checked it's implementation.
c.f. https://github.com/flutter/flutter/blob/v1.5.4-hotfixes/packages/flutter/lib/src/material/app_bar.dart#L586

**Comment by neestell** [comment]
Thanks! it resolves the issue
