### ISSUE TITLE
Running 'flutter run' on a physical device and there is a issue.

### ISSUE THREAD

**Issue by ParthAggarwal1996** [YoussefKababe/admob_flutter#5]
I ran the code by putting all the same codes for Banner Ads as per the instruction by YoussefKababe. But this error appears while running **Android dependency 'com.google.android.gms:play-services-measurement-base' has different version for the compile (16.0.3) and runtime (16.0.4) classpath. You should manually set the same version via DependencyResolution**

Please someone provide me the solution...

**Comment by gcshri** [comment]
https://github.com/YoussefKababe/admob_flutter/issues/3 has the solution 

Use the subprojects snippet to hardwire the dependencies in gradle.

**Comment by kmcgill88** [comment]
Sounds like this has been resolved. Closing for now. If it's still an issue we can re-open later.
