### ISSUE TITLE
Banner ad reloads on Transform.scale

### ISSUE THREAD

**Issue by EliasDeuss** [YoussefKababe/admob_flutter#50]
Find this kinda weird why it's reloading on a Transform.scale

**Comment by EliasDeuss** [comment]
Here is an example:

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/13773566/60644650-9d184680-9deb-11e9-9a7c-9bb0739ba3d2.gif)

**Comment by EliasDeuss** [comment]
@kmcgill88 any idea why this would happen?

**Comment by kmcgill88** [comment]
My best guess without seeing your code is the banner is re-rendered. I noticed this when I implemented the iOS side of things. Each Flutter render creates a new banner ad. I believe the recommended way of implementing banners is to use a single instance in your app (or at least few instances). I've done this natively in the past with [McAdViewController](https://github.com/kmcgill88/McAdViewController). 

I'm speculating that for your use case **you should wrap the banner in a stateful widget to keep it from re-rendering**. However, this won't stop banner recreation if you navigate to different screens.

Specifically, on iOS (Android is identical) the [`dispose`](https://github.com/YoussefKababe/admob_flutter/blob/master/ios/Classes/AdmobBanner.swift#L43) function is called when the widget is re-created which throws out the native banner with it's corresponding `dispose` and then it's created again.

Each banner gets a [`viewId`](https://github.com/YoussefKababe/admob_flutter/blob/master/ios/Classes/AdmobBanner.swift#L27) which I wondered if we could *find* the view back while navigating between screens so banners don't have to be tossed out so frequently. I'd love to hear how Google would suggest implementing banners in Flutter. Aside from [Admob banner guidance doc](https://support.google.com/admob/answer/6128877?hl=en&ref_topic=2745287).

I plan on playing around with banner outside of the `MaterialApp` to keep a single instance app-wide and hopefully outside of the navigation stack. This way you'd only ever have 1 instance of a banner that is always visible, at the top of your widget tree so it is never re-rendered. That's what I do with [McAdViewController](https://github.com/kmcgill88/McAdViewController).

**Comment by EliasDeuss** [comment]
@kmcgill88 Did this and it's still going on. 

```dart
class BannerAdWidget extends StatefulWidget {
  @override
  _BannerAdWidgetState createState() => _BannerAdWidgetState();
}

class _BannerAdWidgetState extends State<BannerAdWidget>
    with AutomaticKeepAliveClientMixin<BannerAdWidget> {
  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Column(
      children: <Widget>[
        Padding(
          padding: new EdgeInsets.only(
            left: 10.0,
            right: 10.0,
          ),
          child: new Divider(
            height: 10.0,
            color: Colors.grey,
          ),
        ),
        Padding(
          padding: new EdgeInsets.only(
            top: 5.0,
            bottom: 5.0,
          ),
          child: AdmobBanner(
            adUnitId: BannerAd.testAdUnitId,
            adSize: AdmobBannerSize.BANNER,
          ),
        ),
      ],
    );
  }
}
```

**Comment by EliasDeuss** [comment]
@kmcgill88 also getting this error 

```
<Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.
```

**Comment by kmcgill88** [comment]
@EliasDeuss I've seen that before too. I don't see it when I use my real Admob Id's. Maybe it's just a test unit id thing?

**Comment by EliasDeuss** [comment]
@kmcgill88 maybe I tried wrapping in a stateful widget but it kept happening.
