### ISSUE TITLE
can admob be used in China?

### ISSUE THREAD

**Issue by MeDeity** [YoussefKababe/admob_flutter#52]
I downloaded the demo and found that the ad can be requested normally, but when I jumped to the ad address, most of it could not be loaded. I was wondering if admob would provide ads for China in China. Simply put, I With expectation, can admob be used in China?

**Comment by EliasDeuss** [comment]
I did a little resich on this and i think it depends on your ISP. Here is one article i found about it that might answer your question. https://birchlabs.co.uk/blog/jamie/linguabrowse/2018/01/28/is-google-admob-blocked-in-china.html @MeDeity

**Comment by MeDeity** [comment]
Thank you 

> Does the Google AdMob pane register any clicks?
I couldn’t test this directly, as it’s against the terms and conditions of Google AdMob to deliberately click on ads, so I had to wait a while for some data to come in...

If the advertisement comes from a Chinese advertiser, I think it can be accessed, at least the advertising address is in China.

**Comment by MeDeity** [comment]
I will try,thx again

**Comment by EliasDeuss** [comment]
No problem @MeDeity Happy to help
