### ISSUE TITLE
AdmobAdEvent.closed listener does not work on iOS with interstitials

### ISSUE THREAD

**Issue by hasen6** [YoussefKababe/admob_flutter#60]
I have it set up so that it listens for the interstitial ad to be closed and then start loading the next one as in the example code. This works fine in android but in iOS it does not detect the `AdmobAdEvent.closed`. Some of the other listener parameters work ok like `AdmobAdEvent.loaded` though.

As you can imagine this is somewhat problematic since it means that on iOS the interstitial will only ever fire once..

I have it set up as in the example code:

```
  void initState() {
    super.initState();
    interstitialAd = AdmobInterstitial(
      adUnitId: 'ca-app-pub-3940256099942544/1033173712',
      listener: (AdmobAdEvent event, Map<String, dynamic> args) {
        if (event == AdmobAdEvent.loaded) print('loaded');
        if (event == AdmobAdEvent.closed) {
          print('closed');
          interstitialAd.load();
        }
      },
    );
  }
```

**Comment by kmcgill88** [comment]
What version of iOS and Flutter?

It should be firing that callback [here](https://github.com/YoussefKababe/admob_flutter/blob/master/ios/Classes/AdmobInterstitialPlugin.swift#L122).

**Comment by hasen6** [comment]
It was the oddest thing. I tried it again and again and it was working with Android, not on iOS with no code changes. Then I just added a `print(event)` to see if anything was being output and then it _all_ started working...after that it suddenly started registering `AdmobAdEvent.closed` in iOS...
