### ISSUE TITLE
Use "flutter_webview_plugin" and "admob_flutter" will produce some errors

### ISSUE THREAD

**Issue by Frank0945** [YoussefKababe/admob_flutter#62]
When I use flutter_webview_plugin and admob_flutter

Generated the following problem：

> Launching lib\main.dart on SM G950F in debug mode...

> D8: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

> FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\57.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\114.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\75.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\81.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\129.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\120.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\69.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\96.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\135.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\102.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\141.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\1.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\105.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\23.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\66.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\90.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\117.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\144.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\54.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\63.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\78.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\108.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\132.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\93.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\147.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\111.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\126.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\123.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\72.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\84.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\99.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\87.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\60.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\138.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\0.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\14.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\31.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\7.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\32.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\8.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\24.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\15.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\5.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\38.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\12.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\25.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\6.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\30.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\26.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\13.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\19.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\36.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\10.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\27.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\37.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\4.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\28.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\11.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\20.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\33.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\16.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\29.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\9.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\21.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\34.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\18.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\17.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\22.jar, C:\Users\user\Documents\GitHub\IG-Story-viewer\build\app\intermediates\transforms\dexBuilder\debug\35.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 20s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by rikiraspoutine** [comment]
same problem here

**Comment by Nisthar** [comment]
@Frank0945 @rikiraspoutine same problem. Found any solution yet?

**Comment by rikiraspoutine** [comment]
> @Frank0945 @rikiraspoutine same problem. Found any solution yet?

no
