### ISSUE TITLE
The ad container shows black color till the add loads.

### ISSUE THREAD

**Issue by narayanansampath** [YoussefKababe/admob_flutter#73]
![Screenshot_20190928-204001](https://user-images.githubusercontent.com/19869271/65818654-0f54c780-e231-11e9-8c47-99efc2c682bf.png)
Any fix for this? Even after setting a background color to the container the problem persists.

**Comment by kmcgill88** [comment]
Closing this as duplicate of https://github.com/YoussefKababe/admob_flutter/issues/31
