### ISSUE TITLE
Doesn't launch debug apk

### ISSUE THREAD

**Issue by sankaraya** [YoussefKababe/admob_flutter#9]
Hi
when I trying this plugin with cloud_firestore    plugin debug apk build failed and give me flowing error.

>FAILURE: Build failed with an exception.
* What went wrong:
Failed to capture fingerprint of input files for task ':app:checkDebugClasspath' property 'runtimeClasspath' during up-to-date check.
> The library com.google.android.gms:play-services-ads-base is being requested by various other libraries at [[15.0.1,15.0.1], [17.1.1,17.1.1]], but resolves to 17.1.1. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 7s
Gradle task assembleDebug failed with exit code 1

### pubspec.yaml flie 
`version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0

  share: ^0.5.3
  flutter_webview_plugin: ^0.3.0+2
  path_provider: ^0.4.1
  sqflite: ^0.13.0
  cloud_firestore: ^0.8.2+3
  firebase_messaging:
  admob_flutter: "^0.1.2"

  
   The following adds the Cupertino Icons font to your application.
  Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

`
/////////////////////////////
*** try flutter doctor 
`$ flutter doctor -v
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.472], locale en-IN)
    • Flutter version 1.0.0 at C:\flu\flutter
    • Framework revision 5391447fae (4 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\BKPK\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.30.1)
    • VS Code at C:\Users\BKPK\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • bkpk • bddda6907d13 • android-arm64 • Android 6.0.1 (API 23)

• No issues found!`

**Comment by gcshri** [comment]
Take a look at forcing dependencies in gradle.

https://github.com/YoussefKababe/admob_flutter/issues/3#issuecomment-448639210

**Comment by sankaraya** [comment]
yeah its working  with test App ID from Admob but not working my Admob App ID
its showing .....
`I/Ads     (26887): No fill from ad server.
W/Ads     (26887): Failed to load ad: 3
I/flutter (26887): Admob banner failed to load. Error code: 3`
